### PR TITLE
Integration

### PR DESCRIPTION
**Pull request by fasaldana**
# Blog app - integration specs for views and fix n+1 problems
## This pull request adds the following features: 
- Refactor code to resolve n+1 concerns
- Integration tests for user index and show
- Integration tests for post index and show 
## To setup database and use the site 
Please run the following commands in the project folder after cloning the repo: `bundle install` `rails db:create` `rails db:migrate` 
## Run tests 
`rspec spec` 

### NOTE ABOUT LOGIN PAGE
Though the requirements request tests for the login page, this has not been a previously requested part of the wireframe build and has yet to be implemented at this stage. Please reference this submitted [issue](https://github.com/microverseinc/curriculum-rails/issues/107) that was submitted to correct this requirement for this project

### CODE REVIEW

**Review by alexander16108 — CHANGES_REQUESTED** [review]
Hi @fasaldana and @AKeeganDev, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Required Changes ♻️
_Check the comments under the review._

### as per the project requirement the should be a test for the following ⏬ 

-  Tests that returns a detailed error when no `username` and `password` is entered when the submit button is clicked
- Tests that returns a detailed error when an incorrect `username` or `password` is entered when the submit button is clicked
- Tests that redirects to the root page when a correct `username` and `password` is entered.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by fasaldana** [comment]
@alexander16108 Though the requirements request tests for the login page, this has not been a previously requested part of the wireframe build and has yet to be implemented at this stage. Please reference this submitted https://github.com/microverseinc/curriculum-rails/issues/107 that was submitted to correct this requirement for this project

Also, my coding partner was able to pass without these tests due to them not being required. Here's the link from my coding partner's PR: https://github.com/AKeeganDev/blog_app/pull/9

**Review by nicupop729 — COMMENTED** [review]
Hello @fasaldana 👋,

_This is an additional review as a result of the second opinion request._

Congratulations on your good work for this milestone and for this project! :clap:
You have done a great job!

And I am happy to let you know that you are right: taking into account that you were not requested to implement the login form, should not be asked from you to test it.
On this basis, your milestone should have been approved!

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approve right away :)

Keep rocking 🚀!

**Comment by fasaldana** [comment]
Thank you @nicupop729 :D

**Review by elmar8287 — APPROVED** [review]
Hi, 

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

### Highlights

- Well done with the implementation of milestone requirements 👍 
- Nice PR description 🥇 
- I liked your informative README file 👍 👍 👍 

### Optional suggestions

- For the future, please, consider giving the title for commit with a Capital letter, to make the commits history looks professional 💯 👍 
- 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
